version: '3.7'
services:
  lotus:
    image: ghcr.io/jimpick/lotus-fvm-localnet-lite:latest
    network_mode: "host"
    command: "lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false"
    ports:
      - "1234:1234"
    volumes:
      - ./target/debug/wbuild/validator:/wbuild/validator

  lotus-miner:
    image: ghcr.io/jimpick/lotus-fvm-localnet-lite:latest
    depends_on:
      - lotus
    network_mode: "host"
    command: bash -c "sleep 2; lotus-miner run --nosync"
